### PR TITLE
Upgrade 2021 extension

### PR DESCRIPTION
**Pull request by thelsing**
This PR extends #5. 

Changes:
- fix build.gradle
- copy html file to classes dir before compiling the java file of the component. If you just put the html file to the compile it end up in the output directory and the compiler uses an old version.

### CODE REVIEW

**Comment by adrienbaron** [comment]
Thank you for this PR! When opening your branch in the latest IntelliJ Ultimate (`#IU-213.6461.79`), I'm getting the following graddle build error:

```
Build file '/Users/adrien/projects/vue-gwt-intellij-plugin/build.gradle' line: 2

An exception occurred applying plugin request [id: 'org.jetbrains.intellij', version: '1.3.0']
> Failed to apply plugin [id 'org.jetbrains.intellij']
   > Could not create an instance of type org.jetbrains.intellij.utils.ArchiveUtils.
      > Could not generate a decorated class for class org.jetbrains.intellij.utils.ArchiveUtils.
         > org/gradle/api/file/ArchiveOperations
```

Does it work on your side for you? Which version of IntelliJ are you using :)?

**Comment by thelsing** [comment]
I have no such error. I use IC-213.5744.223, I have jdk17 in PATH (which gradle complains about but builds nonetheless)

**Comment by adrienbaron** [comment]
Seems like I have an old version of Gradle (`v5.2.1`) 🤦 , I'll try and upgrade 👍

**Comment by thelsing** [comment]
Superseded by #7

**Pull request closed without merging**
